# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotionProtocol

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ODriveStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ODriveStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsODriveStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ODriveStatus
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ODriveStatus
    def Connected0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Connected1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Connected2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Connected3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Connected4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Connected5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ODriveStatus
    def Error00(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error01(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error10(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error11(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error20(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error21(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error30(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error31(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error40(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error41(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error50(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ODriveStatus
    def Error51(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ODriveStatusStart(builder: flatbuffers.Builder):
    builder.StartObject(18)

def Start(builder: flatbuffers.Builder):
    ODriveStatusStart(builder)

def ODriveStatusAddConnected0(builder: flatbuffers.Builder, connected0: bool):
    builder.PrependBoolSlot(0, connected0, 0)

def AddConnected0(builder: flatbuffers.Builder, connected0: bool):
    ODriveStatusAddConnected0(builder, connected0)

def ODriveStatusAddConnected1(builder: flatbuffers.Builder, connected1: bool):
    builder.PrependBoolSlot(1, connected1, 0)

def AddConnected1(builder: flatbuffers.Builder, connected1: bool):
    ODriveStatusAddConnected1(builder, connected1)

def ODriveStatusAddConnected2(builder: flatbuffers.Builder, connected2: bool):
    builder.PrependBoolSlot(2, connected2, 0)

def AddConnected2(builder: flatbuffers.Builder, connected2: bool):
    ODriveStatusAddConnected2(builder, connected2)

def ODriveStatusAddConnected3(builder: flatbuffers.Builder, connected3: bool):
    builder.PrependBoolSlot(3, connected3, 0)

def AddConnected3(builder: flatbuffers.Builder, connected3: bool):
    ODriveStatusAddConnected3(builder, connected3)

def ODriveStatusAddConnected4(builder: flatbuffers.Builder, connected4: bool):
    builder.PrependBoolSlot(4, connected4, 0)

def AddConnected4(builder: flatbuffers.Builder, connected4: bool):
    ODriveStatusAddConnected4(builder, connected4)

def ODriveStatusAddConnected5(builder: flatbuffers.Builder, connected5: bool):
    builder.PrependBoolSlot(5, connected5, 0)

def AddConnected5(builder: flatbuffers.Builder, connected5: bool):
    ODriveStatusAddConnected5(builder, connected5)

def ODriveStatusAddError00(builder: flatbuffers.Builder, error00: int):
    builder.PrependInt32Slot(6, error00, 0)

def AddError00(builder: flatbuffers.Builder, error00: int):
    ODriveStatusAddError00(builder, error00)

def ODriveStatusAddError01(builder: flatbuffers.Builder, error01: int):
    builder.PrependInt32Slot(7, error01, 0)

def AddError01(builder: flatbuffers.Builder, error01: int):
    ODriveStatusAddError01(builder, error01)

def ODriveStatusAddError10(builder: flatbuffers.Builder, error10: int):
    builder.PrependInt32Slot(8, error10, 0)

def AddError10(builder: flatbuffers.Builder, error10: int):
    ODriveStatusAddError10(builder, error10)

def ODriveStatusAddError11(builder: flatbuffers.Builder, error11: int):
    builder.PrependInt32Slot(9, error11, 0)

def AddError11(builder: flatbuffers.Builder, error11: int):
    ODriveStatusAddError11(builder, error11)

def ODriveStatusAddError20(builder: flatbuffers.Builder, error20: int):
    builder.PrependInt32Slot(10, error20, 0)

def AddError20(builder: flatbuffers.Builder, error20: int):
    ODriveStatusAddError20(builder, error20)

def ODriveStatusAddError21(builder: flatbuffers.Builder, error21: int):
    builder.PrependInt32Slot(11, error21, 0)

def AddError21(builder: flatbuffers.Builder, error21: int):
    ODriveStatusAddError21(builder, error21)

def ODriveStatusAddError30(builder: flatbuffers.Builder, error30: int):
    builder.PrependInt32Slot(12, error30, 0)

def AddError30(builder: flatbuffers.Builder, error30: int):
    ODriveStatusAddError30(builder, error30)

def ODriveStatusAddError31(builder: flatbuffers.Builder, error31: int):
    builder.PrependInt32Slot(13, error31, 0)

def AddError31(builder: flatbuffers.Builder, error31: int):
    ODriveStatusAddError31(builder, error31)

def ODriveStatusAddError40(builder: flatbuffers.Builder, error40: int):
    builder.PrependInt32Slot(14, error40, 0)

def AddError40(builder: flatbuffers.Builder, error40: int):
    ODriveStatusAddError40(builder, error40)

def ODriveStatusAddError41(builder: flatbuffers.Builder, error41: int):
    builder.PrependInt32Slot(15, error41, 0)

def AddError41(builder: flatbuffers.Builder, error41: int):
    ODriveStatusAddError41(builder, error41)

def ODriveStatusAddError50(builder: flatbuffers.Builder, error50: int):
    builder.PrependInt32Slot(16, error50, 0)

def AddError50(builder: flatbuffers.Builder, error50: int):
    ODriveStatusAddError50(builder, error50)

def ODriveStatusAddError51(builder: flatbuffers.Builder, error51: int):
    builder.PrependInt32Slot(17, error51, 0)

def AddError51(builder: flatbuffers.Builder, error51: int):
    ODriveStatusAddError51(builder, error51)

def ODriveStatusEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ODriveStatusEnd(builder)
