from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ODriveStatus(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ODriveStatus: ...
  @classmethod
  def GetRootAsODriveStatus(cls, buf: bytes, offset: int) -> ODriveStatus: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Connected0(self) -> bool: ...
  def Connected1(self) -> bool: ...
  def Connected2(self) -> bool: ...
  def Connected3(self) -> bool: ...
  def Connected4(self) -> bool: ...
  def Connected5(self) -> bool: ...
  def Error00(self) -> int: ...
  def Error01(self) -> int: ...
  def Error10(self) -> int: ...
  def Error11(self) -> int: ...
  def Error20(self) -> int: ...
  def Error21(self) -> int: ...
  def Error30(self) -> int: ...
  def Error31(self) -> int: ...
  def Error40(self) -> int: ...
  def Error41(self) -> int: ...
  def Error50(self) -> int: ...
  def Error51(self) -> int: ...
def ODriveStatusStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ODriveStatusAddConnected0(builder: flatbuffers.Builder, connected0: bool) -> None: ...
def ODriveStatusAddConnected1(builder: flatbuffers.Builder, connected1: bool) -> None: ...
def ODriveStatusAddConnected2(builder: flatbuffers.Builder, connected2: bool) -> None: ...
def ODriveStatusAddConnected3(builder: flatbuffers.Builder, connected3: bool) -> None: ...
def ODriveStatusAddConnected4(builder: flatbuffers.Builder, connected4: bool) -> None: ...
def ODriveStatusAddConnected5(builder: flatbuffers.Builder, connected5: bool) -> None: ...
def ODriveStatusAddError00(builder: flatbuffers.Builder, error00: int) -> None: ...
def ODriveStatusAddError01(builder: flatbuffers.Builder, error01: int) -> None: ...
def ODriveStatusAddError10(builder: flatbuffers.Builder, error10: int) -> None: ...
def ODriveStatusAddError11(builder: flatbuffers.Builder, error11: int) -> None: ...
def ODriveStatusAddError20(builder: flatbuffers.Builder, error20: int) -> None: ...
def ODriveStatusAddError21(builder: flatbuffers.Builder, error21: int) -> None: ...
def ODriveStatusAddError30(builder: flatbuffers.Builder, error30: int) -> None: ...
def ODriveStatusAddError31(builder: flatbuffers.Builder, error31: int) -> None: ...
def ODriveStatusAddError40(builder: flatbuffers.Builder, error40: int) -> None: ...
def ODriveStatusAddError41(builder: flatbuffers.Builder, error41: int) -> None: ...
def ODriveStatusAddError50(builder: flatbuffers.Builder, error50: int) -> None: ...
def ODriveStatusAddError51(builder: flatbuffers.Builder, error51: int) -> None: ...
def ODriveStatusEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

